#!/bin/bash
#SBATCH --job-name="Run-GENIE3"
#SBATCH --workdir=.
#SBATCH --output=./logs/GENIE3_%j.out
#SBATCH --error=./logs/GENIE3_%j.err
#SBATCH --cpus-per-task=18
#SBATCH --ntasks=1
#SBATCH --time=01:00:00


module load python/3.7.4

export PATH=/home/bsc08/bsc08890/.local/bin:/home/bsc08/bsc08890/bin:$PATH
export PYTHONPATH=/home/bsc08/bsc08890/.local/lib/python3.7/site-packages:$PYTHONPATH

python run_genie3.py -i ~/res/PilotWorkflow/data/HVG_norm_data.tsv -o ~/res/PilotWorkflow/data/genie3_res.tsv
